# Generated by Django 5.1.3 on 2024-12-29 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player2', to=settings.AUTH_USER_MODEL)),
                ('white_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('move_number', models.IntegerField()),
                ('move_from', models.CharField(max_length=2)),
                ('move_to', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.game')),
            ],
        ),
    ]
