# Generated by Django 5.1.3 on 2025-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_rename_game_gamedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='fen_string',
            field=models.CharField(default='', max_length=90),
        ),
    ]
