# Generated by Django 5.1.3 on 2025-03-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0004_gamedb_black_player2_remaining_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='curr_turn',
            field=models.CharField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='is_bot_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamedb',
            name='black_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
